# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'RNCocoaPodsDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNCocoaPodsDemo
  rn_path = '../node_modules/react-native'

  pod 'Yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'aliyun-oss-react-native', :path => '../node_modules/aliyun-oss-react-native'
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'


end

